services:
  backend:
    build:
      context: ./backend
    ports:
      - "8030:8030"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:8030
    environment:
      VITE_API_BASE_URL: http://localhost:8030
    ports:
      - "3030:3030"
    depends_on:
      - backend
